class AppAssets {
  const AppAssets._();

  static const String _lottie = 'assets/lottie';

  static const String onboarding = '$_lottie/onboarding.json';
  static const String emptyState = '$_lottie/empty_state.json';
  static const String success = '$_lottie/success.json';
  static const String celebration = '$_lottie/celebration.json';

  static const String _icon = 'assets/icon';

  static const String accountCircleOff = '$_icon/account_circle_off.svg';
  static const String add = '$_icon/add.svg';
  static const String addCircle = '$_icon/add_circle.svg';
  static const String addHome = '$_icon/add_home.svg';
  static const String alternateEmail = '$_icon/alternate_email.svg';
  static const String barChart = '$_icon/bar_chart.svg';
  static const String bolt = '$_icon/bolt.svg';
  static const String brokenImage = '$_icon/broken_image.svg';
  static const String category = '$_icon/category.svg';
  static const String checkCircle = '$_icon/check_circle.svg';
  static const String chevronRight = '$_icon/chevron_right.svg';
  static const String close = '$_icon/close.svg';
  static const String cloudOff = '$_icon/cloud_off.svg';
  static const String contentCopy = '$_icon/content_copy.svg';
  static const String currencyRupeeCircle = '$_icon/currency_rupee_circle.svg';
  static const String darkMode = '$_icon/dark_mode.svg';
  static const String delete = '$_icon/delete.svg';
  static const String directionsBus = '$_icon/directions_bus.svg';
  static const String edit = '$_icon/edit.svg';
  static const String editNote = '$_icon/edit_note.svg';
  static const String electricRickshaw = '$_icon/electric_rickshaw.svg';
  static const String email = '$_icon/email.svg';
  static const String folder = '$_icon/folder.svg';
  static const String folderManaged = '$_icon/folder_managed.svg';
  static const String folderOpen = '$_icon/folder_open.svg';
  static const String googleIcon = '$_icon/google_icon.svg';
  static const String history = '$_icon/history.svg';
  static const String home = '$_icon/home.svg';
  static const String inbox = '$_icon/inbox.svg';
  static const String iosShare = '$_icon/ios_share.svg';
  static const String keyboardAlt = '$_icon/keyboard_alt.svg';
  static const String keyboardArrowDown = '$_icon/keyboard_arrow_down.svg';
  static const String lightMode = '$_icon/light_mode.svg';
  static const String localTaxi = '$_icon/local_taxi.svg';
  static const String lock = '$_icon/lock.svg';
  static const String logout = '$_icon/logout.svg';
  static const String movie = '$_icon/movie.svg';
  static const String noPhotography = '$_icon/no_photography.svg';
  static const String notes = '$_icon/notes.svg';
  static const String notificationNone = '$_icon/notification_none.svg';
  static const String notifications = '$_icon/notifications.svg';
  static const String notificationsActive = '$_icon/notifications_active.svg';
  static const String payments = '$_icon/payments.svg';
  static const String personAdd = '$_icon/person_add.svg';
  static const String personOff = '$_icon/person_off.svg';
  static const String photoCamera = '$_icon/photo_camera.svg';
  static const String photoLibrary = '$_icon/photo_library.svg';
  static const String profile = '$_icon/profile.svg';
  static const String qrCodeScanner = '$_icon/qr_code_scanner.svg';
  static const String receipt = '$_icon/receipt.svg';
  static const String restaurant = '$_icon/restaurant.svg';
  static const String savings = '$_icon/savings.svg';
  static const String share = '$_icon/share.svg';
  static const String shield = '$_icon/shield.svg';
  static const String shoppingBag = '$_icon/shopping_bag.svg';
  static const String store = '$_icon/store.svg';
  static const String swapHorizontal = '$_icon/swap_horizontal.svg';
  static const String tag = '$_icon/tag.svg';
  static const String title = '$_icon/title.svg';
  static const String trendingDown = '$_icon/trending_down.svg';
  static const String trendingUp = '$_icon/trending_up.svg';
  static const String warning = '$_icon/warning.svg';
}
